version: "3.9"
# docker system prune для очистки неиспользуемых данных
services:
  
  prometheus: # https://hub.docker.com/r/prom/prometheus
    image: prom/prometheus:latest
    container_name: c2-hw-prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped
    environment:
    volumes:
      - ./etc/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 127.0.0.1:9090:9090
    depends_on:
      
  grafana:
    image:
    container_name: c2-hw-grafana
    restart: unless-stopped
    environment:
    volumes:
    ports:
    depends_on:
      
  node-explorer:
    image:
    container_name: c2-hw-node-explorer
    restart: unless-stopped
    environment:
    volumes:
    ports:
    depends_on:
      
  blackbox-explorer:
    image:
    container_name: c2-hw-blackbox-explorer
    restart: unless-stopped
    environment:
    volumes:
    ports:
    depends_on:
      
  alert-manager: 
    image:
    container_name: c2-hw-alert-manager
    restart: unless-stopped
    environment:
    volumes:
    ports:
    depends_on:
