---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
- name: Create a project directory
  ansible.builtin.file:
    path: /home/roman/c1hw
    state: directory
    mode: '0755'
  become: true

- name: copy Docker Compose files
  ansible.builtin.copy:
    src: ../docker-compose.yml
    dest: /home/roman/c1hw/docker-compose.yml

- name: Create a ssl directory
  ansible.builtin.file:
    path: /home/roman/c1hw/ssl
    state: directory
    mode: '0755'
  become: true

- name: copy ssl files
  ansible.builtin.copy:
    src: ../.secure_files/{{ item }}
    dest: /home/roman/c1hw/ssl/
  with_items:
  - dhparam.pem
  - ssl.crt
  - ssl.key

- name: Create a psk directory
  ansible.builtin.file:
    path: /home/roman/c1hw/psk
    state: directory
    mode: '0755'
  become: true

- name: copy psk files
  ansible.builtin.copy:
    src: ../.secure_files/zabbix.psk
    dest: /home/roman/c1hw/psk/zabbix.psk
    
# 'cmd' is module parameter
- name: Run docker compose
  ansible.builtin.command:
    chdir: /home/roman/c1hw
    cmd: docker-compose up -d
