---
# to start: ansible-playbook -i ../hosts main.yml
- hosts: all
  become: true
  tasks:
 # Update cache
  - name: Update apt repo and cache on Ubuntu box
    ansible.builtin.apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

# Upgrade packeges
  - name: Upgrade all packages on servers
    ansible.builtin.apt:
      upgrade: dist
      force_apt_get: yes

    # Установка докера
  - include_tasks: setupDocker.yml

- hosts: monitoring
  become: true
  tasks:
    # Развертывание проекта на виртуалке
  - include_tasks: deploy.yml